### ISSUE TITLE
Completando o estado no select

### ISSUE THREAD

**Issue by celsoandrade** [arthurfigueiredo/autocomplete-address#5]
Olá,

é possível no retorno selecionar o estado dentro de um dropdown?

Grato

**Comment by arthurfigueiredo** [comment]
Olá,

Sim, só que é necessário que o option tenha o valor da UF.

Nessa linha ele faz isso: 

`$state.children('option:contains("' + values.uf + '")').prop('selected', true);`

**Comment by arthurfigueiredo** [comment]
você pode adaptar o código pra sua necessidade
