### ISSUE TITLE
Dúvidas

### ISSUE THREAD

**Issue by PauloBoaventura** [arthurfigueiredo/autocomplete-address#6]
Este código esta funcionando em PHP 5, 5.6, 7.0, 7.1 ou até mesmo em 7.2 ?
São muitas dúvidas e nada pessoal... (Já deixo claro)
Este código esta nas normativas novas dos correios (2017) e que pelo visto já existe novas normativas em (2018)...
Bom, este não é o único que visualizamos que aparentemente esta tudo correto.
Mas, tenho que ser este USUÁRIO questionador, já que estamos enfrentando tantos problemas seja eles em PHP, AJAX ou qualquer impulso anterior á 2017.
E assim vem as dúvidas...

Gostaria de saber se podemos implementar este código em outras ferramentas e até mesmo em outas plataformas... 

Espero que tenhamos uma resposta satisfatória e um UPGRADE. (O que neste notamos que o upgrade é notavel).

S.O = Centos7 - Plesk
Php = 5.6 / 7.0

**Comment by arthurfigueiredo** [comment]
Bom dia, Paulo, tudo bom?

Esse plugin não possui código PHP, trata-se de um plugin jQuery que integra com a API ViaCEP, ou seja não importa a versão do PHP ou servidor, o requisito é que sua plataforma rode jQuery para utilizar o plugin.

O link da API online é esse: https://viacep.com.br/

Espero ter ajudado.

Abraço,
Arthur

**Comment by PauloBoaventura** [comment]
Olá @arthurfigueiredo 
Compreendi sobre o código deste plugin.
Por um acaso sabe me dizer se posso fazer integração deste plugin com o Magento 1.9 ou 2.1 ?

Agradeço a atenção e aguardo seu contato1

**Comment by arthurfigueiredo** [comment]
Pode, o requisito é só ter o jQuery instalado.
